[program:clearline-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/clearline/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
directory=/var/www/clearline
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/clearline/storage/logs/worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/www/clearline/storage/logs/worker-error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stopwaitsecs=3600
stopsignal=TERM