<script lang="ts">
  import {
    Home,
    MessageSquare,
    Users,
    Inbox,
    Tags,
    BarChart3,
    Settings,
    Building2,
    Megaphone,
    Library,
    Briefcase,
    SquareUser,
    UserCog,
    Code,
    Workflow,
    Bot,
    ToyBrick,
    MessageSquareQuote,
    Blocks,
    ShieldPlus,
    ClockAlert,
    Shield,
    CreditCard,
    Folder,
    Facebook,
    Twitter,
    Mail,
    Globe,
    Smartphone,
    Send,
    MessageCircle,
    Contact,
    Book,
    Bolt,
    ChartSpline,
    LibraryBig
  } from "lucide-svelte";

  let { name, class: className }: { name?: string; class?: string } = $props();

  const icons: Record<string, any> = {
    home: Home,
    "message-square": MessageSquare,
    users: Users,
    inbox: Inbox,
    tags: Tags,
    "bar-chart-3": BarChart3,
    settings: Settings,
    bolt: Bolt,
    "building-2": Building2,
    megaphone: Megaphone,
    library: Library,
    "library-big": LibraryBig,
    briefcase: Briefcase,
    "square-user": SquareUser,
    "user-cog": UserCog,
    code: Code,
    workflow: Workflow,
    bot: Bot,
    "toy-brick": ToyBrick,
    "message-square-quote": MessageSquareQuote,
    blocks: Blocks,
    "shield-plus": ShieldPlus,
    "clock-alert": ClockAlert,
    shield: Shield,
    "credit-card": CreditCard,
    folder: Folder,
    facebook: Facebook,
    twitter: Twitter,
    mail: Mail,
    globe: Globe,
    smartphone: Smartphone,
    send: Send,
    "message-circle": MessageCircle,
    contact: Contact,
    book: Book,
    "chart-spline": ChartSpline
  };

  const Icon = $derived(name && icons[name] ? icons[name] : Home);
</script>

<Icon class={className} />
