[program:clearline-horizon]
process_name=%(program_name)s
command=php /var/www/clearline/artisan horizon
directory=/var/www/clearline
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/clearline/storage/logs/horizon.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/www/clearline/storage/logs/horizon-error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stopwaitsecs=60
stopsignal=TERM